### ISSUE TITLE
FATAL:   container creation failed: while mounting image /proc/self/fd/3: failed to find loop device

### ISSUE THREAD

**Issue by mariabenitocst** [HEP-KBFI/singularity#7]
Encountering the following error:

FATAL:   container creation failed: mount /proc/self/fd/3->/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available

when `sbatch test.sh`

```
#!/bin/bash
#SBATCH --partition=short
#set -x #print out all commands before executing                                
#set -e #abort bash script on error 

IMG=/home/software/singularity/base.simg

singularity exec -B /home  $IMG  python3 test.py 
```

**Comment by jpata** [comment]
solved by recompiling with --sandbox. batch nodes run inside containers already, so mounting loop devices for a container inside the container is not allowed since recent security updates.
